services:
  - type: web
    name: social-crosspost-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: IG_CLIENT_ID
        sync: false
      - key: IG_CLIENT_SECRET
        sync: false
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false

  - type: web
    name: social-crosspost-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://social-crosspost-api.onrender.com/api